export default {
	REMOVE_WALK: 'REMOVE_WALK',
	ADD_WALK: 'ADD_WALK',
	UPDATE_TITLE: 'UPDATE_TITLE',
	UPDATE_DESCRIPTION: 'UPDATE_DESCRIPTION',
	VIEW_LIST: 'VIEW_LIST',
	CREATE_LIST: 'CREATE_LIST',
	WALK_SELECTED: 'WALK_SELECTED',
};

// git